Add configuration to allow specific users to create tags

diff --git a/.github/workflows/create-tag-release.yml b/.github/workflows/create-tag-release.yml
--- a/.github/workflows/create-tag-release.yml
+++ b/.github/workflows/create-tag-release.yml
@@ -15,13 +15,25 @@ env:
   QUAY_ODH_DASHBOARD_IMAGE_REPO: ${{ secrets.QUAY_ODH_DASHBOARD_IMAGE_REPO }}
 
 jobs:
-  delete-pr-quay-image:
+  create-tag:
     runs-on: ubuntu-latest
     steps:
       - name: Git checkout
         uses: actions/checkout@v4
         with:
           fetch-depth: '0'
+      - name: Check authorized user
+        id: auth-check
+        run: |
+          AUTHORIZED_USERS_FILE=".github/workflows/authorized-tag-creators.txt"
+          if [[ ! -f "$AUTHORIZED_USERS_FILE" ]]; then
+            echo "Authorized users file not found!"
+            exit 1
+          fi
+          if ! grep -q "^${GITHUB_ACTOR}$" "$AUTHORIZED_USERS_FILE"; then
+            echo "User ${GITHUB_ACTOR} is not authorized to run this workflow."
+            exit 1
+          fi
       - name: Install podman
         shell: bash
         run: |
@@ -30,11 +42,11 @@ jobs:
       - name: Pull Quay repository
         shell: bash
         run: |
-          podman pull docker://${QUAY_ODH_DASHBOARD_IMAGE_REPO}
+          podman pull ${QUAY_ODH_DASHBOARD_IMAGE_REPO}
       - name: Create new release tag off of latest main-tag
         shell: bash
         run: |
-          podman tag ${QUAY_ODH_DASHBOARD_IMAGE_REPO}:${{ github.event.inputs.existingTag }} docker://${QUAY_ODH_DASHBOARD_IMAGE_REPO}:${{ github.event.inputs.releaseTag }}
+          podman tag odh-dashboard:${{ github.event.inputs.existingTag }} ${QUAY_ODH_DASHBOARD_IMAGE_REPO}:${{ github.event.inputs.releaseTag }}
       - name: Login to quay.io
         shell: bash
         env:
@@ -45,4 +57,4 @@ jobs:
       - name: Push the latest release tag to Quay
         shell: bash
         run: |
-          podman push docker://${QUAY_ODH_DASHBOARD_IMAGE_REPO}:${{ github.event.inputs.releaseTag }}
+          podman push ${QUAY_ODH_DASHBOARD_IMAGE_REPO}:${{ github.event.inputs.releaseTag }}
